/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smartfarm_driver_SerialPort */

#ifndef _Included_com_smartfarm_control_SerialPort
#define _Included_com_smartfarm_control_SerialPort

/*
 * Class:     com_smartfarm_driver_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_smartfarm_control_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_smartfarm_driver_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_smartfarm_control_SerialPort_close
  (JNIEnv *, jobject);


#endif
